version: 2
references:
  ## Workspaces
  #workspace: &workspace
  #Our workspace is the project dir, where fastlane is installed.
    #~/src

  ## Docker image configurations
  android_config: &android_config
    #working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

## Dependencies
  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: bundle check || bundle install --path vendor/bundle

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

jobs:
  build:
    <<: *android_config
    steps:
      - checkout
      - *ruby_dependencies
      - *android_dependencies
      - run:
          name: Initial build
          command: ./gradlew clean build

  ## Run unit tests
  test_unit:
    <<: *android_config
    steps:
      - checkout
      - *ruby_dependencies
      - *android_dependencies
      - run:
          name: Run unit tests
          command: bundle exec SDK_MODULE=$SDK_MODULE fastlane run_all_tests #this still needs to be made a public lane and removed from the main lane
      - store_artifacts:
          path: $SDK_MODULE/build/reports/
          destination: /reports/
      - store_test_results:
          path: $SDK_MODULE/build/test-results/
          destination: /test-results/

  deployment:
      type: approval
      docker:
        - image: ubuntu
      steps:
        - checkout
        - run: echo test

workflows:
  version: 2
  workflow1:
    jobs:
      - build
      - test_unit:
          requires:
            - build
      - deployment_approval:
          type: approval
          requires:
           - test
      - deployment:
          requires:
            - deployment_approval