version: 2
references:

  android_config: &android_config
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

  bootstrap: &bootstrap
    run:
      name: Bootstrap
      command: |
        git clone "${SA_CONTINUOUS_INTEGRATION_GIT_REPO_URL}" "${SA_PATH_TO_CONTINUOUS_INTEGRATION_REPO}"
        ${SA_PATH_TO_CONTINUOUS_INTEGRATION_REPO}/bootstrap/bootstrap-mobile-android-sdk.sh

jobs:

  ## Run unit tests
  test_unit:
    <<: *android_config
    steps:
      - checkout
      - *bootstrap
      - run:
          name: Run unit tests
          command: fastlane run_all_tests
      - run:
          name: Copy test results to temp folder
          command: find $PWD/$SA_ANDROID_SDKS_MODULE/build/test-results/testDebugUnitTest -name '*.xml' -exec cp {} ${PWD}/temp_files/test-results/debug \;
      - store_test_results:
          path: temp_files/test-results

  semantic_release:
    <<: *android_config
    steps:
      - checkout
      - run:
          name: Run semantic release
          command: |
            git clone "${SA_CONTINUOUS_INTEGRATION_GIT_REPO_URL}" "${SA_PATH_TO_CONTINUOUS_INTEGRATION_REPO}"
            ${SA_PATH_TO_CONTINUOUS_INTEGRATION_REPO}/semantic-release/semantic-release.sh

  ## Run sdk push
  sdk_push:
    <<: *android_config
    steps:
      - checkout
      - *bootstrap
      - run:
          name: Push the SDK to the bintrayRepo
          command: fastlane sdk_push isPrivateRepo:${SA_MOBILE_IS_PUSH_TO_PRIVATE_REPO}

  sdk_push_public:
    <<: *android_config
    steps:
      - checkout
      - *bootstrap
      - run:
          name: Push the SDK to the PUBLIC bintrayRepo
          command: fastlane sdk_push isPrivateRepo:false

workflows:
  version: 2
  android_sdk_workflow:
    jobs:
      - test_unit:
          context: MOBILE_ANDROID_SDKS
      - semantic_release:
          context: MOBILE_ANDROID_SDKS
          requires:
            - test_unit
          filters:
            branches:
              only: master
      - sdk_push:
          context: MOBILE_ANDROID_SDKS
          requires:
            - semantic_release
      - sdk_push_public:
          context: MOBILE_ANDROID_SDKS
          requires:
            - semantic_release
            