version: 2
## Declare de references
references:
  ## Docker image configurations
  android_config: &android_config
    #working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

## Dependencies
  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: bundle check || bundle install --path vendor/bundle

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  fastlane_dependencies: &fastlane_dependencies
    run:
      name: Download fastlane
      command: gem install fastlane

  fastlane_plugin: &fastlane_plugin
    run:
      name: Download fastlane plugin for Android
      command: fastlane add_plugin android_versioning


jobs:
  build:
    <<: *android_config
    steps:
      - checkout
      - *ruby_dependencies
      - *android_dependencies
      - run:
          name: Initial build
          command: ./gradlew clean build

  ## Run unit tests
  test_unit:
    <<: *android_config
    steps:
      - checkout
      - *ruby_dependencies
      - *android_dependencies
      - *fastlane_dependencies
      - *fastlane_plugin
      - run:
          name: Run unit tests
          command: bundle exec fastlane run_all_tests
      - store_test_results:
          path: $SDK_MODULE/build/test-results

  deployment:
      docker:
        - image: ubuntu
      steps:
        - checkout
        - run: echo test

workflows:
  version: 2
  workflow1:
    jobs:
      - build
      - test_unit:
          requires:
            - build
      - deployment_approval:
          type: approval
          requires:
           - test_unit
      - deployment:
          requires:
            - deployment_approval